---
title: ARTEMIS-DELFI scores predict survival for patients in PACTO trial
---


Kaplan-Meier curves of progression free survival probability and overall survival probability based on median landmark ARTEMIS-DELFI score at 8 weeks. Patients are classified as responders or non-responders if follow-up ARTEMIS-DELFI scores are below or above the median follow-up score, respectively.


```{r packages, message = FALSE}
library(here)
library(tidyverse)
library(ggpubr)
library(survival)
library(survminer)
library(readxl)
```


```{r load_data}
clean_data <- read_excel(here("data/supplementary_tables.xlsx"),
                         sheet = "Table S4", range = "A2:T42")
delfi_pred <- read_excel(here("data/supplementary_tables.xlsx"),
                         sheet = "Table S5", range = "A2:L207")
```


```{r ext-fig23a, fig.height = 7, fig.width = 15, dev = c("png", "pdf")}
delfi_pred <- delfi_pred %>%
  filter(Timepoint == "Endpoint", `ARTEMIS-DELFI Score` != "-")
delfi_pred$`ARTEMIS-DELFI Score` <- as.numeric(delfi_pred$`ARTEMIS-DELFI Score`)
DELFI_complete <- inner_join(delfi_pred, clean_data, by = "Patient")
DELFI_complete <- DELFI_complete %>%
  mutate(cutoff1 = ifelse(`ARTEMIS-DELFI Score` >= median(`ARTEMIS-DELFI Score`),
                          "Nonresponder", "Responder"))
DELFI_complete <- DELFI_complete %>%
  mutate(across("Deceased", str_replace, "Yes", "1"),
         across("Deceased", str_replace, "No", "0"))
DELFI_complete$`OS (days)` <- as.numeric(DELFI_complete$`OS (days)`)
DELFI_complete$`PFS (days)` <- as.numeric(DELFI_complete$`PFS (days)`)
DELFI_complete$Deceased <- as.numeric(DELFI_complete$Deceased)

p <- vector("list", 2)

fit <- survfit(Surv(`PFS (days)`, Deceased) ~ cutoff1, data=DELFI_complete)

p[[1]] <- fit %>%
  ggsurvplot(pval = TRUE, risk.table = TRUE, risk.table.col = "strata",
             surv.median.line = "hv",
             #title="PFS based on median ARTEMIS-DELFI w8",
             ylab="Progression free survival probability",
             xlab="Time in Days",
             ggtheme = theme_classic2(base_size=11),
             legend = c(.9, .75),
             legend.title="",
             legend.labs=c("nonresponder", "responder"),
             pval.size=3,
             pval.coord = c(400, .25),
             tables.y.text = FALSE)

p[[1]]$plot <- p[[1]]$plot +
  annotate("text", x = 500, y = 0.95,
           label = "ARTEMIS-DELFI molecular\nassessment (8 weeks)",
           size = 3, hjust = 0)

fit <- survfit(Surv(`OS (days)`, Deceased) ~ cutoff1, data=DELFI_complete)

p[[2]] <- fit %>%
  ggsurvplot(pval = TRUE, risk.table = TRUE, risk.table.col = "strata",
             surv.median.line = "hv",
             #title="OS based on median ARTEMIS-DELFI w8",
             xlab="Time in Days",
             ylab="Overall survival probability",
             ggtheme = theme_classic2(base_size=11),
             legend = c(.9,.75),
             legend.title=element_blank(),
             legend.labs=c("nonresponder","responder"),
             pval.size=3, pval.coord = c(600, .25),tables.y.text = FALSE)

p[[2]]$plot <- p[[2]]$plot +
  annotate("text", x = 750, y = 0.95,
           label = "ARTEMIS-DELFI molecular\nassessment (8 weeks)",
           size = 3, hjust = 0)

arrange_ggsurvplots(p, nrow = 1)

coxPFS <- coxph(Surv(`PFS (days)`, Deceased) ~ cutoff1, data = DELFI_complete)
summary(coxPFS)

coxOS <- coxph(Surv(`OS (days)`, Deceased) ~ cutoff1, data = DELFI_complete)
summary(coxOS)
```
