---
title: WGMAF stratifies progression free and overall survival for patients in the CheckPAC trial with stable disease
---


Kaplan-Meier curves of progression free survival probability and overall survival probability based on landmark WGMAF value at 8-week timepoint, limited to patients assessed as having stable disease at the first follow-up CT scan.


```{r packages, message = FALSE}
library(ggpubr)
library(here)
library(readxl)
library(survival)
library(survminer)
library(tidyverse)
```


```{r load_data}
clean_data <- read_excel(here("data/supplementary_tables.xlsx"),
                         sheet = "Table S1", range = "A2:X45")
wgsmaf_pred <- read_excel(here("data/supplementary_tables.xlsx"),
                          sheet = "Table S2", range = "A2:N219")
exclude_ids <- c("CGPLPA796", "CGPLPA792", "CGPLPA791", "CGPLPA773",
                 "CGPLPA779", "CGPLPA226", "CGPLPA222")
```


```{r ext-fig6, fig.height = 7, fig.width = 15, dev = c("png", "pdf")}
WGSMAF_complete <- wgsmaf_pred %>%
  filter(!Patient %in% exclude_ids) %>%
  filter(Timepoint == "Endpoint", WGMAF != "-") %>%
  inner_join(clean_data, by = "Patient") %>%
  mutate(WGMAF = as.numeric(WGMAF)) %>%
  mutate(cutoff1 = ifelse(WGMAF >= median(WGMAF),
                          "Nonresponder", "Responder")) %>%
  mutate(across("Death", str_replace, "Yes", "1"),
         across("Death", str_replace, "No", "0")) %>%
  mutate(`OS (days)` = as.numeric(`OS (days)`),
         `PFS (days)` = as.numeric(`PFS (days)`),
         `Deceased` = as.numeric(Death)) %>%
  filter(`RECIST at FU 1` == "Stable Disease")

p <- vector("list", 2)

fit <- survfit(Surv(`PFS (days)`, Deceased) ~ cutoff1, data = WGSMAF_complete)

p[[1]] <- fit %>%
  ggsurvplot(pval = TRUE, risk.table = TRUE, risk.table.col = "strata",
             surv.median.line = "hv",
             #title = "PFS based on WGMAF median cutoff",
             xlab = "Time in Days",
             ylab = "Progression free survival probability",
             ggtheme = theme_classic2(base_size = 11),
             legend = c(.9, .75),
             legend.title = element_blank(),
             legend.labs = c("nonresponder", "responder"),
             pval.size = 3, pval.coord = c(1800, .25), tables.y.text = FALSE)

p[[1]]$plot <- p[[1]]$plot +
  annotate("text", x = 1650, y = 0.9,
           label = "WGMAF molecular\nassessment (8 weeks)",
           size = 3, hjust = 0)

fit <- survfit(Surv(`OS (days)`, Deceased) ~ cutoff1, data = WGSMAF_complete)

p[[2]] <- fit %>%
  ggsurvplot(pval = TRUE, risk.table = TRUE, risk.table.col = "strata",
             surv.median.line = "hv",
             #title = "OS based on WGMAF median cutoff",
             xlab = "Time in Days",
             ylab = "Overall survival probability",
             ggtheme = theme_classic2(base_size = 11),
             legend = c(.9, .75),
             legend.title = element_blank(),
             legend.labs = c("nonresponder", "responder"),
             pval.size = 3, pval.coord = c(1800, .25), tables.y.text = FALSE)

p[[2]]$plot <- p[[2]]$plot +
  annotate("text", x = 1650, y = 0.9,
           label = "WGMAF molecular\nassessment (8 weeks)",
           size = 3, hjust = 0)

arrange_ggsurvplots(p, nrow = 1)

coxPFS <- coxph(Surv(`PFS (days)`, Deceased) ~ cutoff1, data = WGSMAF_complete)
summary(coxPFS)

coxOS <- coxph(Surv(`OS (days)`, Deceased) ~ cutoff1, data = WGSMAF_complete)
summary(coxOS)
#write_csv(WGSMAF_complete, here("data/system.csv"))
```
