---
title: Change in DELFI-TF scores between baseline and 8 week time point scores are predictive of progression free and overall survival in CheckPAC trial
---


Kaplan-Meier curves of progression free survival probability and overall survival probability based on increase or decrease in DELFI-TF score at 8-week timepoint


```{r packages, message = FALSE}
library(ggpubr)
library(here)
library(readxl)
library(survival)
library(survminer)
library(tidyverse)
```


```{r load_data}
clean_data<-read_excel(here("data/supplementary_tables.xlsx"),
                       sheet="Table S1",range="A2:X45")
delfitf_pred<-read_excel(here("data/supplementary_tables.xlsx"),
                         sheet="Table S2",range="A2:P219")
```


```{r ext-fig21a, fig.height = 7, fig.width = 15, dev = c("png", "pdf")}
delfitf_pred_endpoint <- delfitf_pred %>%
  filter(Timepoint == "Endpoint") %>%
  mutate(`DELFI-TF` = as.numeric(`DELFI-TF`)) %>%
  rename(DTF = `DELFI-TF`)

delfitf_pred_baseline <- delfitf_pred %>%
  filter(Timepoint == "Baseline") %>%
  mutate(`DELFI-TF` = as.numeric(`DELFI-TF`)) %>%
  rename(DTF = `DELFI-TF`)

delfitf_complete <- delfitf_pred_endpoint %>%
  select(Patient, DTF) %>%
  inner_join(select(delfitf_pred_baseline, Patient, DTF),
             by = "Patient", suffix = c("_endpoint", "_baseline")) %>%
  inner_join(clean_data, by = "Patient") %>%
  mutate(mag = DTF_baseline / DTF_endpoint,
         cutoff1 = ifelse(mag >=1, "Responder", "Nonresponder")) %>%
  mutate(across('Death', str_replace, 'Yes', '1'),
        across('Death', str_replace, 'No', '0'))
delfitf_complete$`OS (days)`<-as.numeric(delfitf_complete$`OS (days)`)
delfitf_complete$`PFS (days)`<-as.numeric(delfitf_complete$`PFS (days)`)
delfitf_complete$Deceased<-as.numeric(delfitf_complete$Death)

p <- vector("list", 2)

fit <- survfit(Surv(`PFS (days)`, Deceased) ~ cutoff1, data=delfitf_complete)

p[[1]] <- fit %>%
  ggsurvplot(pval = TRUE, risk.table = TRUE, risk.table.col = "strata",
             surv.median.line = "hv",
             #title="Progression free survival based on DELFI monitoring change%",
             ylab="Progression free survival probability",
             xlab="Time in Days",
             ggtheme = theme_classic2(base_size=11),
             legend = c(.9,.75),
             legend.title=element_blank(),
             legend.labs=c("nonresponder","responder"),
             pval.size=3, pval.coord = c(1800, .25),tables.y.text = FALSE)

p[[1]]$plot <- p[[1]]$plot +
  annotate("text", x = 1650, y = 0.9,
           label = "DELFI-TF molecular\nassessment (8 weeks)",
           size = 3, hjust = 0)

fit <- survfit(Surv(`OS (days)`, Deceased) ~ cutoff1, data=delfitf_complete)

p[[2]] <- fit %>%
  ggsurvplot(pval = TRUE, risk.table = TRUE, risk.table.col = "strata",
             surv.median.line = "hv",
             #title="Overall survival based on DELFI monitoring change",
             xlab="Time in Days",
             ylab="Overall survival probability",
             ggtheme = theme_classic2(base_size=11),
             legend = c(.9,.75),
             legend.title=element_blank(),
             legend.labs=c("nonresponder","responder"),
             pval.size=3, pval.coord = c(1800, .25),tables.y.text = FALSE)

p[[2]]$plot <- p[[2]]$plot +
  annotate("text", x = 1650, y = 0.9,
           label = "DELFI-TF molecular\nassessment (8 weeks)",
           size = 3, hjust = 0)

arrange_ggsurvplots(p, nrow = 1)

coxPFS <- coxph(Surv(`PFS (days)`, Deceased) ~ cutoff1, data = delfitf_complete)
summary(coxPFS)

coxOS <- coxph(Surv(`OS (days)`, Deceased) ~ cutoff1, data = delfitf_complete)
summary(coxOS)
```
