---
title: Landmark CA19-9 levels show limited correlation with response for patients in CheckPAC trial
---


Boxplot showing log10 of CA19-9 concentration, sorted by baseline, and follow-up for patients with PD, SD, and PR. Wilcoxon P values are indicated above each comparison.


```{r packages}
library(ggpubr)
library(here)
library(readxl)
library(tidyverse)
```


```{r load_data}
clean_data<-read_excel(here("data/supplementary_tables.xlsx"), sheet="Table S1",range="A2:W45")
CA199<-read_csv(here("data/CA199.csv")) %>%
  filter(timepoint!="follow up")
clean_data$`Study ID`<-as.character(clean_data$`Study ID`)
CA199$ca199<-as.numeric(CA199$ca199)
CA199$`Study ID`<-as.character(CA199$subject_id)
```

```{r  ext-fig16a, fig.width=3.5, fig.height=7, dev = c("png", "pdf")}
DELFI_complete<-inner_join(CA199, clean_data, by="Study ID")
DELFI_complete<-DELFI_complete %>% mutate(class = case_when((timepoint == "Baseline") ~ "Baseline",
                                        TRUE ~ `BOR RECIST 1.1`))
DELFI_complete<-DELFI_complete %>% filter(`BOR RECIST 1.1`!="Not Evaluable")

DELFI_complete<-DELFI_complete %>% mutate(class = case_when((class  == "Baseline") ~ "Baseline",
                                                            (class == "Stable Disease") ~ "SD",
                                                            (class == "Partial Response") ~ "PR",
                                                            (class == "Progressive Disease") ~ "PD"))

DELFI_complete<-DELFI_complete %>% filter(`Study ID`!="85",`Study ID`!="94",`Study ID`!="99",`Study ID`!="1104")

DELFI_complete$class <- factor(DELFI_complete$class, levels = c("Baseline","PD","SD","PR"), ordered = TRUE)

my_comparisons <- list(c("SD", "PR"), c("PD", "PR"),c("Baseline","PR"))

ggplot(DELFI_complete, aes(x=class, y=ca199, fill=class)) + 
  geom_boxplot(outlier.shape = NA)+   stat_compare_means(comparisons = my_comparisons)+ ylab("log 10 of CA19-9")+ theme_classic()+scale_fill_manual(values=c("#C77CFF","#F8766D","#00BFC4","#7CAE00"))+ scale_y_continuous(trans='log10')+ geom_point(alpha=1/3, position=position_jitter(0.2), size=.8)
```
