---
title: ARTEMIS-DELFI scores predict survival for patients in CheckPAC trial 
---


Kaplan-Meier curves of progression free survival probability and overall survival probability based on “fast-fail” landmark ARTEMIS-DELFI score after one cycle of treatment (2 weeks). Patients are classified as responders or non-responders if follow-up ARTEMIS-DELFI scores are below or above the median follow-up score, respectively


```{r packages, message = FALSE}
library(caret)
library(data.table)
library(devtools)
library(ggpubr)
library(here)
library(lubridate)
library(readxl)
library(recipes)
library(survival)
library(survminer)
library(tidyverse)
```


```{r load_data}
clean_data<-read_excel(here("data/supplementary_tables.xlsx"), sheet="Table S1",range="A2:X45")
delfi_pred<-read_excel(here("data/supplementary_tables.xlsx"), sheet="Table S2",range="A2:N219")
```


```{r fig6c,  fig.height=6, fig.width=6, dev = c("png", "pdf")}
delfi_pred<-delfi_pred %>% filter(Timepoint=="cycle 1",`ARTEMIS-DELFI Score`!="-")
delfi_pred$`ARTEMIS-DELFI Score`<-as.numeric(delfi_pred$`ARTEMIS-DELFI Score`)
DELFI_complete<-inner_join(delfi_pred,clean_data, by="Patient")
DELFI_complete<-DELFI_complete %>% mutate(class1 = case_when((`ARTEMIS-DELFI Score` >= .967) ~ "High",
                                                           .default = "Not High"))
DELFI_complete<-DELFI_complete %>% mutate(across('Death', str_replace, 'Yes', '1'))
DELFI_complete<-DELFI_complete %>% mutate(across('Death', str_replace, 'No', '0'))
DELFI_complete$`OS (days)`<-as.numeric(DELFI_complete$`OS (days)`)
DELFI_complete$`PFS (days)`<-as.numeric(DELFI_complete$`PFS (days)`)
DELFI_complete$Deceased<-as.numeric(DELFI_complete$Death)

fit <- survfit(Surv(`PFS (days)`, Deceased) ~ class1, data=DELFI_complete)
ggsurvplot(fit, pval = TRUE, risk.table = TRUE, risk.table.col = "strata", surv.median.line = "hv", title="PFS based on ARTEMIS-DELFI top quartile week 2", ylab="Progression free survival probability", xlab="Time in Days", ggtheme = theme_classic2(base_size=11), legend = c(.9,.75), legend.labs=c("nonresponder","responder"), legend.title="", pval.size=3, pval.coord = c(700, .25),tables.y.text = FALSE) 

coxPFS <- coxph(Surv(`PFS (days)`, Deceased) ~ class1, data = DELFI_complete)
summary(coxPFS)

fit <- survfit(Surv(`OS (days)`, Deceased) ~ class1, data=DELFI_complete)
ggsurvplot(fit, pval = TRUE, risk.table = TRUE, risk.table.col = "strata", surv.median.line = "hv", title="OS based on ARTEMIS-DELFI top quartile week 2", xlab="Time in Days", ylab="Overall survival probability", ggtheme = theme_classic2(base_size=11), legend = c(.9,.75), legend.labs=c("nonresponder","responder"), legend.title="", pval.size=3, pval.coord = c(1500, .25),tables.y.text = FALSE) 

coxOS <- coxph(Surv(`OS (days)`, Deceased) ~ class1, data = DELFI_complete)
summary(coxOS)
```
