---
title: ARTEMIS-DELFI scores predict survival for patients in CheckPAC trial
---


Boxplot of ARTEMIS-DELFI scores for all patients with plasma samples at baseline, and at follow-up for each of the clinical RECIST 1.1 response categories


```{r packages, message=FALSE}
library(data.table)
library(devtools)
library(ggpubr)
library(here)
library(lubridate)
library(readxl)
library(survival)
library(survminer)
library(tidyverse)
```


```{r load_data, message = FALSE}
clean_data<-read_excel(here("data/supplementary_tables.xlsx"), sheet="Table S1",range="A2:W45")
delfi_pred<-read_excel(here("data/supplementary_tables.xlsx"), sheet="Table S2",range="A2:N219")
```


```{r fig6a, fig.height=7, fig.width=3.5, dev = c("png", "pdf")}
delfi_pred<-delfi_pred %>% filter(Timepoint!="follow up", Timepoint!="cycle 1", `ARTEMIS-DELFI Score`!="-")
delfi_pred$`ARTEMIS-DELFI Score`<-as.numeric(delfi_pred$`ARTEMIS-DELFI Score`)
DELFI_complete<-inner_join(delfi_pred,clean_data, by="Patient")
DELFI_complete<-DELFI_complete %>% mutate(class = case_when((Timepoint == "Baseline") ~ "Baseline",
                                        TRUE ~ `BOR RECIST 1.1`))
DELFI_complete<-DELFI_complete %>% filter(`BOR RECIST 1.1`!="Not Evaluable")


DELFI_complete<-DELFI_complete %>% mutate(class = case_when((class  == "Baseline") ~ "Baseline",
                                                            (class == "Stable Disease") ~ "SD",
                                                            (class == "Partial Response") ~ "PR",
                                                            (class == "Progressive Disease") ~ "PD"))

DELFI_complete$class <- factor(DELFI_complete$class, levels = c("Baseline","PD","SD","PR"), ordered = TRUE)
my_comparisons <- list(c("SD", "PR"),c("PD", "PR"),c("Baseline","PR"))

ggplot(DELFI_complete, aes(x=class, y=`ARTEMIS-DELFI Score`, fill=`class`)) +
  geom_boxplot(outlier.shape=NA)+ stat_compare_means(comparisons = my_comparisons) +
  scale_fill_manual(values=c("#C77CFF", "#F8766D","#00BFC4","#7CAE00")) +
  geom_point(alpha=1/3, position=position_jitter(0.2), size=.8) +
  ylab("ARTEMIS-DELFI scores") +
  theme_classic()
```
